# Generated by Django 5.0.6 on 2024-12-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank_hdfc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=100, unique=True)),
                ('user_type', models.TextField()),
                ('card_number', models.PositiveBigIntegerField(unique=True)),
                ('cvv', models.PositiveIntegerField(max_length=3, unique=True)),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
    ]
