# Generated by Django 5.1.2 on 2024-12-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hdfc', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bank_hdfc',
        ),
    ]
