# Generated by Django 5.1.2 on 2024-12-08 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hdfc', '0002_delete_bank_hdfc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('account_type', models.CharField(choices=[('ngo', 'NGO'), ('user', 'User')], max_length=20)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts',
                'constraints': [models.CheckConstraint(condition=models.Q(('account_type__in', ['ngo', 'user'])), name='account_type_check'), models.CheckConstraint(condition=models.Q(('account_status__in', ['active', 'inactive', 'closed'])), name='account_status_check')],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=128)),
                ('expiry_date', models.DateField()),
                ('cvv', models.CharField(max_length=128)),
                ('pin_code', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('expired', 'Expired')], max_length=20)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='hdfc.account')),
            ],
            options={
                'db_table': 'cards',
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['active', 'blocked', 'expired'])), name='status_check')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_status', models.CharField(choices=[('successful', 'Successful'), ('pending', 'Pending'), ('failed', 'Failed')], max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='hdfc.account')),
            ],
            options={
                'db_table': 'transactions',
                'constraints': [models.CheckConstraint(condition=models.Q(('transaction_status__in', ['successful', 'pending', 'failed'])), name='transaction_status_check')],
            },
        ),
    ]
