# Generated by Django 5.1.2 on 2024-12-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdfc', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.CharField(max_length=5),
        ),
    ]
