# Generated by Django 5.1.2 on 2024-12-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdfc', '0004_alter_card_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_id',
        ),
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='0000000000000000', max_length=16),
        ),
    ]
