# Generated by Django 5.1.2 on 2024-12-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hdfc', '0005_remove_account_account_id_account_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='pin_code',
        ),
    ]
