"""
Django settings for Bank project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

PRIVATE_KEY = "-----BEGIN RSA PRIVATE KEY-----\nMIICXAIBAAKBgHESw/RFlN9vW9p/uO/JPK7Hc37pqAlg2oHzw0SVTdKw+SuO9eSD\n0M+QwqFuCB8BbGK3Gi0gA1GZbkpfQgFxJbnHbY0+qLD/dLaG+ddzeDBqnJ5CKPNe\nMZQALIZzSLfIbZoVDxzT/mm93Nv5GQlFHiPNOb8Hu6nC0/kVbFFrg1hbAgMBAAEC\ngYAQu3gn04weLDppcPEK+rpyGq2qoCTvjleHV20T3wwvG2Uj3vngIOlrbb5/aOrm\nu60wRmwnNU+Iaa36b3IzCG1OiABpNzJyiUwOWy4475V/UVX5uE62Wl18jHHKXSIW\nk9cez1jvmcOUSg3Z6mDQVCsQN5X7KzXWuYRJcGYkNorLYQJBALit1SmLH3NQfwPn\n004gWmVpA9mGVVqpBsculs8pK+rCDOmQpwaJBo5aKZlb/n1nTUNQJDCtsd5X31Kz\nGv+YFBMCQQCcva5F6ArFJM6GK4NHpeUmew8TrXm3Mmt9I/rBn5SUMDTipPmcl7PP\n8vA+MduA08/eluiuKkSRJgVCIJ7iNGOZAkEAgHbLVL6l/fz8nabhYfM3bluChgnf\nzdTOFjfeR/SHzCF4AfDRfsZKfTNSxI8tk+YL5MsWoZXxqIzPmCNmoG0VaQJAHuUs\nks74QH/OzZeKGvdSQdGD2UcadMfVdCdBaCUCbmtKIVqPcRRd9yFVxYyiTbRyhteM\nKbhfJ5Us+Cnh54iYEQJBAIJ3kfLwSoonpZ3fqOGRcnFUQFOlVU/zgLAHNVR3D7be\nXXxEpzuzqFnLauJB+9KgXCrm9D4TfZGuzBH967zaDsw=\n-----END RSA PRIVATE KEY-----\n"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sgidjdd!)p4*t8w)#ey-$wwb%pf7!m53j(ug9t_4m_+9h+5%cl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hdfc',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Bank.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Bank.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'Bank',  # Replace with your database name
        'USER': 'postgres',       # Replace with your PostgreSQL username
        'PASSWORD': 'root',   # Replace with your PostgreSQL password
        'HOST': '127.0.0.1',           # Set to 'localhost' if running locally
        'PORT': '5432',                # Default PostgreSQL port
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
